name = 'journey'
description = 'A premium SPA theme for technical bloggers'

[mediaTypes]
  [mediaTypes.'application/json']
    suffixes = ['json']

[outputFormats]
  [outputFormats.JSON]
    mediaType = 'application/json'
    baseName = 'index'
    isPlainText = true
    notAlternative = true
  [outputFormats.SEARCHINDEX]
    mediaType = 'application/json'
    baseName = 'search-index'
    isPlainText = true
    notAlternative = true

[outputs]
  taxonomy = ['JSON']
  term     = ['JSON']
  home     = ['HTML', 'JSON', 'SEARCHINDEX']
  page     = ['JSON']
  section  = ['JSON']

[taxonomies]
  tag = "tags"
  series = "series"

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

